version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    tty: true
    restart: always
    environment:
      POSTGRES_DB: universidade
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
